[build]
  command = "invoke publish"
  publish = "output"

[build.environment]
  SITE_RECAPTCHA_KEY = "6Lem_TAUAAAAAPg4MkoXqxCGXkU7DNoCC0Jollvk"
  TZ = "Asia/Jakarta"
  LANGUAGE = "id_ID:id"
  LC_ALL = "id_ID.utf8"
  LOCALE = "id_ID.utf8"
